### PR TITLE
Adding room discover to fix #3

### LINKED ISSUE #3: [Suggestion] Room Discovery
Room Discovery, a page that allows users to browse different **public rooms**.

### PR DESCRIPTION
**Pull request by santhitak**
### Adding a room discovery button to home page
image

### Room discovery page
image

### Reroute to `/{room.id}`
image
<br>

### How to test
0: Pull source code from [here ](https://github.com/santhitak/that-paper-game) to test before merge request.
1: Create a room and put room id in **Discovery.svelte** `room ID value`
2: Open [the-paper-game](http://localhost:3000/) in new tab(e.g. incognito tab) then click on **room discovery button**
3: You will see it appear on the page, click on the room id and it will reroute to your existing room.

## `Feel free to ask questions or give some suggestions, I'm very comfortable fixing or changing anything. Thank you!`

<br><br>

### CODE REVIEW

**Comment by santhitak** [comment]
### How to test
0: Pull source code from [here ](https://github.com/santhitak/that-paper-game) to test before merge request.
1: Create a room and put room id in **Discovery.svelte** `room ID value`
2: Open [the-paper-game](http://localhost:3000/) in new tab(e.g. incognito tab) then click on **room discovery button**
3: You will see it appear on the page, click on the room id and it will reroute to your existing room.

**Comment by narze** [comment]
image
it doesn't show new room 🤔

**Comment by santhitak** [comment]
> image it doesn't show new room 🤔

Yeah, I only did my mock room id and it worked. As I mentioned that I don't know how to fetch the real-time Room ID. Only you put the fetch value in, it'll work. Can you try that? I wonder, too.

**Comment by narze** [comment]
Maybe you can create another webrtc room by creating new store like syncedstore
```
const webrtcProvider = new WebrtcProvider(`that-paper-game-lobby` ...)
```
Then add the created room id to that store

**Comment by santhitak** [comment]
> Maybe you can create another webrtc room by creating new store like syncedstore
> 
> ```
> const webrtcProvider = new WebrtcProvider(`that-paper-game-lobby` ...)
> ```
> 
> Then add the created room id to that store

Thank you, I'll try my best!

**Pull request closed without merging**
